spring.application.name=springaicrud

# Server
server.port=${PORT:8080}
spring.main.allow-circular-references=false

# Render PostgreSQL
spring.datasource.url=jdbc:postgresql://dpg-d7b1hiogjchc73a3nsl0-a.singapore-postgres.render.com:5432/springaicrud_db
spring.datasource.username=springaicrud_db_user
spring.datasource.password=LL0u0Dpz1Ic5bZMQCdknPsDirFknZGZa
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# Ollama (Spring AI)
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.model=llama3
spring.ai.ollama.chat.options.temperature=0.7

# File Upload
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

app.upload.images-dir=src/main/resources/images

server.error.include-message=always

jwt.secret=springaicrud_super_secret_key_2026_secure
jwt.expiration=86400000

# Email Configuration (Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your_email@gmail.com
spring.mail.password=your_app_password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

#  Fine Configuration
fine.per.day=10.00
fine.due.days=14

# Enable Scheduling
spring.task.scheduling.enabled=true

# Rate Limiting
rate.limit.requests.per.minute=60
rate.limit.requests.per.hour=500
rate.limit.auth.per.minute=5
rate.limit.auth.per.hour=20

# Security
security.allowed.origins=http://localhost:3000,https://spring-ai-crud-1.onrender.com
security.max.input.length=1000
security.enable.sql.protection=true